;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        sp-backward-delete-char
        sp-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        ))
