;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        asm-comment
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        crux-move-beginning-of-line
        electric-newline-and-maybe-indent
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-kill-hybrid-sexp
        sp-kill-region
        wdired-finish-edit
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        markdown-outdent-or-delete
        ))
